art049/odmantic

.github/workflows/docs.yml, docs/examples_src/usage_fastapi/base_example.py, docs/examples_src/usage_fastapi/example_delete.py, docs/examples_src/usage_fastapi/example_update.py, docs/usage_fastapi.md, odmantic/fastapi.py, pyproject.toml, tests/fastapi/test_dependency.py
Deprecate `AIOEngineDependency` and recommend to use a global `engine` object to reduce the verbosity required to use the engine.
=> Simpler FastAPI usage

docs/filtering.md
As per issue #23 
Added the Python Bitwise operator warning found in Documentation [API Reference > odmantic.query](https://art049.github.io/odmantic/api_reference/query/#odmantic.query.QueryExpression) to [Filtering > Logical Operators' section](https://art049.github.io/odmantic/filtering/#logical-operators) as well. 
This will be a useful reminder to those who forget to add parenthesis when using bitwise operator comparisons and may overlook the API Reference section which explains why it's necessary to do so..
=> Update Filtering.md to include Bitwise Operator Warning

.github/workflows/ci.yml, CHANGELOG.md, docs/examples_src/usage_pydantic/custom_encoders.py, docs/mkdocs.yml, docs/modeling.md, docs/usage_pydantic.md, odmantic/config.py, odmantic/model.py, odmantic/typing.py, odmantic/utils.py, tests/fastapi/test_models.py, tests/unit/test_json_serialization.py, tests/unit/test_model_definition.py, tests/zoo/person.py
=> Use a Config class to configure models

docs/api_reference/exceptions.md, docs/engine.md, docs/examples_src/raw_query_usage/create_from_raw.py, docs/examples_src/raw_query_usage/parse_with_unset_default.py, docs/examples_src/raw_query_usage/parse_with_unset_default_factory.py, docs/examples_src/raw_query_usage/parse_with_unset_default_factory_enabled.py, docs/fields.md, docs/modeling.md, docs/raw_query_usage.md, odmantic/config.py, odmantic/engine.py, odmantic/exceptions.py, odmantic/field.py, odmantic/model.py, tests/fastapi/test_models.py, tests/integration/test_engine.py, tests/integration/test_engine_reference.py, tests/unit/test_field.py, tests/unit/test_model_logic.py
=> Allow parsing document with unset fields defaults

odmantic/engine.py
Fixes #69 Not authorized on `database` to execute command
`bypass_document_validation` required additional role, that's why it raises `Not authorized` for basic `readWrite` role
=> Remove `bypass_document_validation` save option to avoid `Not Authorized` errors

odmantic/bson.py
Don't replace field description for ObjectId with `MongoDB ObjectId string`
Let developer to define own description for an ObjectId field :)
Fixes #79
=> Don't replace field description for ObjectId

odmantic/engine.py
`__fields_modified__` cleared also for embedded models on save
Fixes #87
=> Fix modified mark clearing on save for nested models

odmantic/model.py
=> fix missing f string issue #163

docs/engine.md, docs/examples_src/engine/create_with_session.py, docs/examples_src/engine/create_with_transaction.py, odmantic/engine.py, tests/integration/test_engine_reference.py
🐛 Fix using the shared session when updating a document
Currently, the code creates a session and transaction and passes down the session in the parameters through all the function calls, but it's not passed in the last point, which would make motor use the session.
The original intention of this PR was just to pass that `session`, a one-line/argument change, but I found a couple of bugs and caveats along the way and the PR got bigger.
~I'm not sure I should add tests for this, I was trying to add them but I saw that I would have to add a bunch of mocks for the internals, or add strange tricks to break the save in the middle and see that the session didn't finish... but then any of those things seemed like a very complex trick to enable a test that would mostly test the trick, and not …
=> 🐛 Fix using the shared session when updating a document

.github/workflows/ci.yml, .pre-commit-config.yaml, README.md, docs/contributing.md, odmantic/bson.py, odmantic/model.py, pyproject.toml, tests/integration/conftest.py, tests/integration/test_types.py, tox.ini
✨ Upgrade types and add support for instance autocompletion with dataclass_transform (VS Code autocompletion).
This is more or less the same as: https://github.com/art049/odmantic/pull/229, and this PR would superseded that one (if accepted). This PR upgrades mypy, the pre-commit, typing-extensions, the necessary types for the new mypy, and adds again `dataclass_transform` with the definitive version (importing from `typing`).
**Edit 2022-06-23**: I realized that the new parameters for `dataclass_transform` require `typing_extensions` version `4.2.0`, but that version doesn't have support for Python 3.6. So this specific PR would depend on dropping support for Python 3.6. 🤦
=> ✨ Upgrade types and add support for instance autocompletion with dataclass_transform (VS Code autocompletion), drop support for Python 3.6

odmantic/model.py
Fix _BaseODMModel.doc containing referenced models with primary_field != id
For example:
```
class X(Model):
key: str = Field(primary_field=True)
class Y(Model):
x_referenced: X = Reference()
```
Saving Y model previously would not work, due to expecting the reference property "x_referenced" to have a property "id"
=> _BaseODMModel.doc fix

odmantic/bson.py, tests/unit/test_bson_fields.py
Treats the following as valid datetime string values:
* `2018-11-02T23:59:01.824` (assumed to be UTC)
* `2018-11-02T23:59:01.824Z` (UTC in simplified extended ISO format)
* `2018-11-02T23:59:01.824+00:00` (GMT, equivalent to UTC)
Fixes #135.
=> Allow models to contain string-based datetime fields that indicate UTC

odmantic/engine.py, tests/integration/test_embedded_model.py
=> Fix save using an embedded model as a primary key

.codecov.yml, .github/workflows/ci.yml, Taskfile.yml, odmantic/exceptions.py, odmantic/field.py, odmantic/model.py, odmantic/typing.py, pyproject.toml, tests/integration/test_embedded_model.py, tests/integration/test_engine.py, tests/unit/test_model_definition.py, tests/unit/test_model_logic.py, tests/unit/test_typing.py, tox.ini
=> Fix `EmbeddedModel` generics definition with a custom `key_name`

mypy.ini, odmantic/engine.py, odmantic/model.py, odmantic/query.py, odmantic/typing.py, pyproject.toml, tests/integration/test_types.py, tests/test_typing_utils.py, tests/typing_utils.py, tests/unit/test_model_definition.py, tests/unit/test_model_type_validation.py
Continues #220 created by @erny 
Closes #200 and will fix #66 
Type equality tests are failing because of https://github.com/python/cpython/issues/97543
=>  Create new types instead of changing type args for structural types

.github/workflows/ci.yml
👷 Pin tox to fix CI
It seems CI is currently failing because `tox` probably introduced an incompatibility in a recent release: https://tox.wiki/en/latest/faq.html#breaking-changes-in-tox-4
I don't know what the problem is, I'm not familiar with Tox, but this PR pins tox to the latest `3.x.x` version available to fix CI that currently is failing.
=> 👷 Pin tox to fix CI

odmantic/model.py, tests/unit/test_field.py
This fixes #407 .
The fix avoids the hack to dynamically generate a Union type instance which will just modify the existing Union[int, str] instance and re-use it for any type annotated with Union.
=> Support defining multiple optional fields with different types

odmantic/bson.py
The function automatically adds an example that changes all the time (date.now())
In my opinion that's a wrong practice and we should let every developer to decide on that.
=> Fix changing example

tests/unit/test_model_definition.py
Add a regression test for #379. Kudos to @netomi again!
=> chore: add a test with a model when defining multiple optional fields

.devcontainer/Dockerfile, .github/workflows/ci.yml, .pre-commit-config.yaml, Taskfile.yml, pyproject.toml
=> make dev container work

.github/workflows/codspeed.yml
Upgrading to the v2 of https://github.com/CodSpeedHQ/action will bring a better base run selection algorithm, better logging, and continued support.
=> chore(bench): update CodSpeed/action to v2
